# Generated by Django 4.0.1 on 2022-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('JobOfferID', models.AutoField(primary_key=True, serialize=False)),
                ('JobOfferName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfOffer', models.DateField()),
                ('LogoPhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
